# Generated by Django 4.0 on 2022-01-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_shopcube', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='category',
        ),
    ]
